print("Enter your name")
a=str(input())
print("Where do you belong ?")
b=str(input())
print("Your college ?")
c=str(input())
print("Your stream ?")
d=str(input())
print("Your registration no. ?")
e=int(input())
print(a)
print(b)
print(c)
print(d)
print(e)    